### ISSUE TITLE
Docker compatibility error

### ISSUE THREAD

**Issue by wallaby-gopher** [RFnexus/Retipedia#2]
Retipeida/nomadnet claims to not be able to find a folder that exists. 
I'm using docker because it's usually more stable for deployments.

The error in nomadnet:
```
[2025-05-30 14:16:34] [Error]    Error occurred while handling request <bb99c3ebf4e9548769de101ecc2cde77> for: /page/Retipedia/index.mu

[2025-05-30 14:16:34] [Error]    The contained exception was: [Errno 2] No such file or directory: '/root/.nomadnetwork/storage/pages/Retipedia/index.mu'

```

The error shown in the client:

![Image](https://github.com/user-attachments/assets/4b7a3ec7-9a5e-4a2b-b4d1-a92bcc5b8138)

The docker-compose:
```
volumes:
  #reticulum
  reticulum:
  nomadnet:
 
services:
  reticulum:
    image: ghcr.io/markqvist/nomadnet:master
    build:
        dockerfile_inline: |
            FROM ghcr.io/markqvist/nomadnet:master
            #install everything, copy files make executable and edit settings
            RUN apk add git \
                && pip install libzim --break-system-packages \
                && pip install beautifulsoup4 --break-system-packages \
                && git clone https://github.com/RFnexus/Retipedia.git \
                && mkdir -p root/.nomadnetwork/storage/pages/ \
                && cp -r Retipedia root/.nomadnetwork/storage/pages/ \
                && chmod +x root/.nomadnetwork/storage/pages/Retipedia/*.mu \
                && sed -i 's+""+"wikipedia/wikipedia_en_all_maxi_2024-01.zim"+' root/.nomadnetwork/storage/pages/Retipedia/settings.py
    init: true
    pull_policy: always
    tty: true #to keep it running
    network_mode: "service:glueads"
    container_name: "reticulum"
    command: --daemon --console
    volumes:
      - reticulum:/root/.reticulum/
      - nomadnet:/root/.nomadnetwork/
      - /media/8tb/wikipedia:/wikipedia
      - type: bind
        source: /media/server/server/ads/config
        target: /root/.reticulum/config
      - type: bind
        source: /media/server/server/ads/nconfig
        target: /root/.nomadnetwork/config
    #to access usb for rnode serial
    devices:
      - "/dev/ttyACM0"
    restart: always
```
the settings.py

![Image](https://github.com/user-attachments/assets/5283a56e-525d-41b1-ae53-744d3cc45aef)

the index indeed being where it is supposed to be

![Image](https://github.com/user-attachments/assets/87824306-a6a4-4de5-b8a1-2b52e99375f2)

The zim location

![Image](https://github.com/user-attachments/assets/542ac9c3-824c-495e-a43c-b0b21f0f8d58)

Please advise.
